[project]
name = 'pytrf'
version = '1.0'
description = 'Python toolbox for the analysis of time series and terrestrial reference frames'
readme = 'README.md'
license = 'MIT'
authors = [
  { name = 'Paul Rebischung', email = 'paul.rebischung@ign.fr' },
  { name = 'Julien Barneoud', email = 'julien.barneoud@ign.fr' },
  { name = 'Kevin Gobron', email = 'gobron@ipgp.fr' },
  { name = 'Maylis de La Serve', email = 'maylis.teyssendierdelaserve@ign.fr' },
]
dependencies = [
  'tqdm',
  'pyyaml',
  'platformdirs',
  'numpy',
  'scipy',
  'networkx',
  'astropy',
  'matplotlib',
  'cartopy',
  'pdoc3',
  'geopandas'
]

[project.urls]
homepage = 'https://github.com/IGNF/pytrf'

[build-system]
requires = ['setuptools>=64']
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
where = ["."]
include = ["pytrf*"]
